# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c8f2a327eece73d0076257b04d00f6bc8ad6e0c571f02c8e9ce9bb5fee126dfb36850326290c2429c62e2c7310723720ce88232b854361196fd966c56219b53

test:
  secret_key_base: 2eef8b8c6d54d2392b4f92177839934fbfae9f843f7ffc190ac745f398b0e838ee4a8fa34bc71eabc09fb03c26ddcfa5425c23aa13ba18c0dfd8fe1df3896fb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
